#region Copyright & License

# Copyright © 2012 - 2021 François Chabot & Emmanuel Benitez
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#endregion

stages:
  - stage: release
    displayName: "Release stage"
    dependsOn: build
    condition: succeeded()
    variables:
      - group: "powershell-gallery"
    jobs:
      - job: publish
        pool:
          vmImage: "windows-latest"
          workspace:
            clean: all
        displayName: "Create github release, publish package on nuget.org and publish pwsh modules on PowerShell Gallery"
        steps:
          - checkout: self
            submodules: true

          - template: /Steps/download-all-build-artifacts.yml
            parameters:
              DownloadPath: "$(System.ArtifactsDirectory)"
              ArtifactPattern: "@(PowerShellModules|NugetPackages|BizTalkPackages)"

          - template: /Steps/create-github-release.yml
            parameters:
              AssetFilePattern: "$(System.ArtifactsDirectory)/BizTalkPackages/*.zip"

          - template: /Steps/nuget-push-to-nuget-org.yml
            parameters:
              Path: "$(System.ArtifactsDirectory)/NugetPackages"

          - template: /Steps/push-powershell-modules-on-powershell-gallery.yml
            parameters:
              RootModulesFolderPath: "$(System.ArtifactsDirectory)/PowerShellModules"
              PowerShellGalleryApiKey: $(powershell-gallery-api-key)
